apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    argocd/app-name: ${{ values.name }}
    github.com/project-slug: jppol-idp/${{ values.name }}
    grafana/overview-dashboard: "https://grafana.jppol.click/goto/Hw7n7PzHR?orgId=1"
    grafana/dashboard-selector: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=${{ values.name }}"
    prometheus.io/rule: container_memory_usage_bytes{pod=~"${{ values.name }}-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"${{ values.name }}-.*"}[5m])|pod
    kubecost.com/deployment-name: ${{ values.name | dump }}
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
    - url: https://grafana.jppol.click/goto/JCdVqlzHg?orgId=1
      title: Grafana loki Access log explorer
      icon: grafana
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: ${{ values.lifecycle }}
