name: Docker Publish
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      REPOSITORY: idp/${{ values.name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Assume AWS IAM Role
      id: assume-role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::970547334392:role/github_actions
        role-skip-session-tagging: true
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #REPOSITORY: {{ env.REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update values.yaml
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd helm
        # git fetch origin
        # git checkout -b deploy origin/deploy
        sed -i "s|tag: .*|tag: ${IMAGE_TAG}|g" values.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add values.yaml
        git commit -m "Update values.yaml"
        git push
